n = int(input("diga um numero"))
print("O seu numero e {}, o cara que vem antes e {}, e o cara que vem depois e {}".format(n,n-1,n+1))
N = int(input("diga-me outro numero? "))
print("O dobro do numero {}, e o {}, agora o triplo e {}".format(N, N*2,N*3))
input("Enter pra sair.")